export default function AiReviewPage() {
  return (
    <div>
      <h1 className="mb-4 text-2xl font-bold">AI-generated content review</h1>
      <p className="text-gray-600">
        Queue of DRAFT exercises generated by Claude is shown here. UI is implemented in the next
        phase (post-MVP-0).
      </p>
    </div>
  );
}
