/**
 * Seed items: GRAMMAR_PATTERN (4 per grammar concept, 48 total).
 *
 * Granularity rule: one item = one thing a learner can get wrong
 * independently. IDs are stable ("item.<concept-short>.<slug>") to make the
 * seed upsert idempotent — same convention as Concept IDs.
 */

import type { SeedItem } from './types';

function gp(
  conceptId: string,
  slug: string,
  cefrLevel: SeedItem['cefrLevel'],
  pattern: string,
  example: string,
  explanationEn: string,
  explanationRu: string,
  extras?: {
    contrastExample?: string;
    usageNoteEn?: string;
    usageNoteRu?: string;
  },
): SeedItem {
  return {
    id: `item.${conceptId.replace('grammar.', '')}.${slug}`,
    conceptId,
    kind: 'GRAMMAR_PATTERN',
    cefrLevel,
    content: {
      source: {
        pattern,
        example,
        ...(extras?.contrastExample ? { contrastExample: extras.contrastExample } : {}),
      },
      localized: {
        explanation: { en: explanationEn, ru: explanationRu },
        ...(extras?.usageNoteEn
          ? {
              usageNote: {
                en: extras.usageNoteEn,
                ...(extras.usageNoteRu ? { ru: extras.usageNoteRu } : {}),
              },
            }
          : {}),
      },
    },
  };
}

export const GRAMMAR_ITEMS: SeedItem[] = [
  // ── grammar.articles_basic ────────────────────────────────────────────────
  gp(
    'grammar.articles_basic',
    'a_an_first_mention',
    'A2',
    'a/an + singular countable (first mention)',
    'I saw a dog in the park.',
    'Use a/an when mentioning a singular countable noun for the first time.',
    'Используйте a/an при первом упоминании исчисляемого существительного в единственном числе.',
  ),
  gp(
    'grammar.articles_basic',
    'the_known_reference',
    'A2',
    'the + known/unique reference',
    'The dog was very friendly.',
    'Use the when both speaker and listener know which thing is meant.',
    'Используйте the, когда и говорящий, и слушающий знают, о чём речь.',
  ),
  gp(
    'grammar.articles_basic',
    'an_before_vowel_sound',
    'A2',
    'an + vowel SOUND',
    'an hour, an umbrella — but a university',
    'Choose an before a vowel sound, not a vowel letter.',
    'Выбирайте an перед гласным ЗВУКОМ, а не буквой.',
    { contrastExample: "a hour (wrong — 'hour' starts with a vowel sound)" },
  ),
  gp(
    'grammar.articles_basic',
    'zero_article_general',
    'A2',
    '∅ article + plural/uncountable (general meaning)',
    'Dogs are loyal. Water is essential.',
    'No article with plurals and uncountables in a general sense.',
    'Без артикля с множественным числом и неисчисляемыми в общем значении.',
  ),

  // ── grammar.plurals ───────────────────────────────────────────────────────
  gp(
    'grammar.plurals',
    'regular_s_es',
    'A2',
    'noun + -s / -es',
    'cat → cats, box → boxes, city → cities',
    '-es after -s/-sh/-ch/-x; consonant + y → -ies.',
    '-es после -s/-sh/-ch/-x; согласная + y → -ies.',
  ),
  gp(
    'grammar.plurals',
    'irregular_common',
    'A2',
    'irregular plurals',
    'child → children, man → men, foot → feet',
    'High-frequency irregular plurals must be memorized as forms.',
    'Частотные неправильные формы множественного числа нужно запоминать.',
  ),
  gp(
    'grammar.plurals',
    'uncountable_no_plural',
    'A2',
    'uncountable = no plural, no a/an',
    'some information, some advice',
    'Uncountables (information, advice, money) take no plural and no a/an.',
    'Неисчисляемые (information, advice, money) не имеют множественного числа и не сочетаются с a/an.',
    { contrastExample: 'informations, an advice (wrong)' },
  ),
  gp(
    'grammar.plurals',
    'same_form_plurals',
    'B1',
    'zero-change plurals',
    'one sheep → two sheep, one fish → two fish',
    'Some nouns keep the same form in singular and plural.',
    'Некоторые существительные не меняют форму во множественном числе.',
  ),

  // ── grammar.comparatives ──────────────────────────────────────────────────
  gp(
    'grammar.comparatives',
    'er_est_short',
    'A2',
    'short adj + -er / -est',
    'tall → taller → the tallest; big → bigger → the biggest',
    'One-syllable adjectives take -er/-est; final consonant doubles after a short vowel.',
    'Односложные прилагательные получают -er/-est; конечная согласная удваивается после краткой гласной.',
  ),
  gp(
    'grammar.comparatives',
    'more_most_long',
    'A2',
    'more / the most + long adjective',
    'expensive → more expensive → the most expensive',
    'Adjectives of 2+ syllables (mostly) use more/most instead of -er/-est.',
    'Прилагательные из 2+ слогов (в основном) используют more/most вместо -er/-est.',
    { contrastExample: 'expensiver (wrong)' },
  ),
  gp(
    'grammar.comparatives',
    'irregular_good_bad',
    'A2',
    'irregular: good/bad/far',
    'good → better → the best; bad → worse → the worst',
    'good, bad, far have suppletive comparative forms.',
    'good, bad, far имеют супплетивные формы сравнения.',
  ),
  gp(
    'grammar.comparatives',
    'than_and_as_as',
    'A2',
    'comparative + than; as + adj + as',
    'She is taller than me. He is as tall as his father.',
    'than after comparatives; as...as for equality.',
    'than после сравнительной степени; as...as для равенства.',
  ),

  // ── grammar.prepositions_time_place ───────────────────────────────────────
  gp(
    'grammar.prepositions_time_place',
    'in_time',
    'A2',
    'in + month/year/season/parts of day',
    'in July, in 2026, in winter, in the morning',
    'in for longer periods: months, years, seasons, parts of the day.',
    'in для длительных периодов: месяцы, годы, сезоны, части дня.',
  ),
  gp(
    'grammar.prepositions_time_place',
    'on_time',
    'A2',
    'on + day/date',
    'on Monday, on 5 May, on my birthday',
    'on for days and dates.',
    'on для дней недели и дат.',
  ),
  gp(
    'grammar.prepositions_time_place',
    'at_time',
    'A2',
    'at + clock time/points',
    "at 7 o'clock, at noon, at night, at the weekend",
    'at for precise points in time and fixed expressions (at night).',
    'at для точного времени и устойчивых выражений (at night).',
  ),
  gp(
    'grammar.prepositions_time_place',
    'in_on_at_place',
    'A2',
    'in (enclosed) / on (surface) / at (point)',
    'in the room, on the table, at the bus stop',
    'in = inside a space, on = on a surface, at = at a point/location.',
    'in = внутри пространства, on = на поверхности, at = в точке/месте.',
  ),

  // ── grammar.question_formation ────────────────────────────────────────────
  gp(
    'grammar.question_formation',
    'yes_no_do_does',
    'A2',
    'Do/Does + subject + V1?',
    'Do you like coffee? Does she work here?',
    'Yes/no questions in Present Simple use do/does before the subject; the verb stays base.',
    'Общие вопросы в Present Simple используют do/does перед подлежащим; глагол в начальной форме.',
    { contrastExample: 'Does she works here? (wrong)' },
  ),
  gp(
    'grammar.question_formation',
    'wh_word_order',
    'A2',
    'Wh- + do/does/did + subject + V1?',
    'Where do you live? What did he say?',
    'Wh-word first, then auxiliary, then subject, then base verb.',
    'Сначала вопросительное слово, затем вспомогательный глагол, подлежащее и основа глагола.',
  ),
  gp(
    'grammar.question_formation',
    'be_inversion',
    'A2',
    'Am/Is/Are + subject ...?',
    'Are you ready? Is she a doctor?',
    'With be, invert subject and verb — no do-support.',
    'С глаголом be — инверсия подлежащего и глагола, без do.',
    { contrastExample: 'Do you be ready? (wrong)' },
  ),
  gp(
    'grammar.question_formation',
    'subject_questions_no_do',
    'B1',
    'Who/What + V (subject question)',
    'Who called you? What happened?',
    'When the wh-word IS the subject, there is no do-support.',
    'Если вопросительное слово — подлежащее, do не используется.',
    { contrastExample: 'Who did call you? (wrong in neutral speech)' },
  ),

  // ── grammar.present_simple ────────────────────────────────────────────────
  gp(
    'grammar.present_simple',
    'third_person_s',
    'A2',
    'he/she/it + V-s',
    'She works in a bank.',
    'Third-person singular adds -s in affirmative Present Simple.',
    'Третье лицо единственного числа получает -s в утвердительной форме Present Simple.',
    { contrastExample: 'She work in a bank. (wrong)' },
  ),
  gp(
    'grammar.present_simple',
    'negative_dont_doesnt',
    'A2',
    "don't/doesn't + V1",
    "He doesn't smoke. They don't live here.",
    "Negatives use don't/doesn't + base verb — the -s moves to does.",
    "Отрицание: don't/doesn't + начальная форма — окончание -s переходит в does.",
    { contrastExample: "He doesn't smokes. (wrong)" },
  ),
  gp(
    'grammar.present_simple',
    'habits_adverbs',
    'A2',
    'Present Simple + frequency adverbs',
    'I usually get up at 7. She never eats meat.',
    'Habits and routines; frequency adverbs go before the main verb.',
    'Привычки и распорядок; наречия частотности стоят перед смысловым глаголом.',
  ),
  gp(
    'grammar.present_simple',
    'schedules_future',
    'B1',
    'Present Simple for timetables',
    'The train leaves at 9:15 tomorrow.',
    'Fixed schedules (transport, programmes) use Present Simple even for future.',
    'Расписания (транспорт, программы) используют Present Simple даже для будущего.',
  ),

  // ── grammar.present_continuous ────────────────────────────────────────────
  gp(
    'grammar.present_continuous',
    'form_be_ving',
    'A2',
    'am/is/are + V-ing',
    'She is reading now.',
    'Form: be (am/is/are) + present participle.',
    'Форма: be (am/is/are) + причастие настоящего времени.',
  ),
  gp(
    'grammar.present_continuous',
    'now_vs_around_now',
    'A2',
    'actions now / temporary situations',
    "I'm staying with friends this week.",
    'Happening at or around the moment of speaking; temporary states.',
    'Действие в момент речи или около него; временные ситуации.',
  ),
  gp(
    'grammar.present_continuous',
    'future_arrangements',
    'B1',
    'Present Continuous for arrangements',
    "We're meeting Anna on Friday.",
    'Fixed personal arrangements with a set time use Present Continuous.',
    'Личные договорённости с назначенным временем — Present Continuous.',
  ),
  gp(
    'grammar.present_continuous',
    'stative_verbs_no_ing',
    'B1',
    'stative verbs avoid -ing',
    'I know the answer. (not: I am knowing)',
    'know, like, want, believe, need describe states, not actions — no continuous.',
    'know, like, want, believe, need описывают состояния — континуус не используется.',
    { contrastExample: 'I am knowing the answer. (wrong)' },
  ),

  // ── grammar.past_simple ───────────────────────────────────────────────────
  gp(
    'grammar.past_simple',
    'regular_ed',
    'A2',
    'V1 + -ed (regular)',
    'worked, played, studied, stopped',
    '-ed spelling: y→ied after consonant; final consonant doubles after short stressed vowel.',
    'Правописание -ed: y→ied после согласной; удвоение конечной согласной после краткой ударной гласной.',
  ),
  gp(
    'grammar.past_simple',
    'irregular_v2',
    'A2',
    'irregular V2 forms',
    'go → went, see → saw, buy → bought',
    'High-frequency irregular past forms must be memorized.',
    'Частотные неправильные формы прошедшего времени нужно запоминать.',
  ),
  gp(
    'grammar.past_simple',
    'negative_didnt',
    'A2',
    "didn't + V1",
    "I didn't see him yesterday.",
    "Negatives use didn't + base verb — the past marking moves to did.",
    "Отрицание: didn't + начальная форма — показатель прошедшего переходит в did.",
    { contrastExample: "I didn't saw him. (wrong)" },
  ),
  gp(
    'grammar.past_simple',
    'questions_did',
    'A2',
    'Did + subject + V1?',
    'Did you finish the report?',
    'Questions use did + base verb.',
    'Вопросы: did + начальная форма глагола.',
    { contrastExample: 'Did you finished? (wrong)' },
  ),

  // ── grammar.past_participle ───────────────────────────────────────────────
  gp(
    'grammar.past_participle',
    'regular_v3_equals_v2',
    'B1',
    'regular V3 = V2 (-ed)',
    'work → worked → worked',
    'For regular verbs the past participle equals the past simple form.',
    'У правильных глаголов причастие прошедшего времени совпадает с формой Past Simple.',
  ),
  gp(
    'grammar.past_participle',
    'irregular_v3_distinct',
    'B1',
    'irregular V3 ≠ V2',
    'go → went → gone; see → saw → seen; do → did → done',
    'Many irregular verbs have a third form distinct from V2 — learn triples.',
    'У многих неправильных глаголов третья форма отличается от V2 — учите тройки.',
    { contrastExample: 'I have went (wrong) → I have gone' },
  ),
  gp(
    'grammar.past_participle',
    'v3_same_all_forms',
    'B1',
    'invariant verbs (put/cut/cost)',
    'put → put → put; cut → cut → cut',
    'Some verbs keep one form across V1/V2/V3.',
    'Некоторые глаголы сохраняют одну форму во всех трёх позициях.',
  ),
  gp(
    'grammar.past_participle',
    'v3_after_have_be',
    'B1',
    'V3 after have (perfect) / be (passive)',
    'She has finished. The house was built in 1990.',
    'V3 follows have in perfect tenses and be in the passive voice.',
    'V3 следует за have в перфектных временах и за be в пассивном залоге.',
  ),

  // ── grammar.present_perfect_basic ─────────────────────────────────────────
  gp(
    'grammar.present_perfect_basic',
    'form_have_v3',
    'B1',
    'have/has + V3',
    'I have seen that film. She has finished.',
    'Form: have/has + past participle.',
    'Форма: have/has + причастие прошедшего времени.',
  ),
  gp(
    'grammar.present_perfect_basic',
    'experience_ever_never',
    'B1',
    'experience: ever / never',
    "Have you ever been to Japan? I've never tried sushi.",
    'Life experience without a specific time — ever in questions, never in negatives.',
    'Жизненный опыт без указания времени — ever в вопросах, never в отрицаниях.',
  ),
  gp(
    'grammar.present_perfect_basic',
    'recent_just_already_yet',
    'B1',
    'just / already / yet',
    "I've just eaten. She's already left. Have you finished yet?",
    'just = very recently; already = sooner than expected; yet = in questions/negatives, at the end.',
    'just = только что; already = раньше ожидаемого; yet = в вопросах/отрицаниях, в конце.',
  ),
  gp(
    'grammar.present_perfect_basic',
    'for_since_unfinished',
    'B1',
    'for + period / since + starting point',
    "I've lived here for five years / since 2021.",
    'Unfinished states: for + duration, since + starting moment.',
    'Незавершённые состояния: for + длительность, since + точка отсчёта.',
    { contrastExample: 'since five years (wrong)' },
  ),

  // ── grammar.modal_verbs_basic ─────────────────────────────────────────────
  gp(
    'grammar.modal_verbs_basic',
    'can_ability',
    'A2',
    "can/can't + V1 (ability)",
    "She can swim. I can't drive.",
    'Present ability and possibility; bare infinitive follows.',
    'Способность и возможность в настоящем; далее — инфинитив без to.',
    { contrastExample: 'She can to swim / She cans swim (wrong)' },
  ),
  gp(
    'grammar.modal_verbs_basic',
    'could_past_ability',
    'A2',
    'could + V1 (past ability / polite)',
    'I could read at five. Could you help me?',
    'Past ability and polite requests.',
    'Способность в прошлом и вежливые просьбы.',
  ),
  gp(
    'grammar.modal_verbs_basic',
    'should_advice',
    'A2',
    "should/shouldn't + V1 (advice)",
    'You should see a doctor.',
    'Advice and recommendations.',
    'Советы и рекомендации.',
  ),
  gp(
    'grammar.modal_verbs_basic',
    'must_obligation',
    'A2',
    "must/mustn't + V1 (obligation/prohibition)",
    "You must wear a seatbelt. You mustn't smoke here.",
    "Strong obligation; mustn't = prohibition, not absence of necessity.",
    "Сильное обязательство; mustn't = запрет, а не отсутствие необходимости.",
    {
      usageNoteEn: "Don't confuse mustn't (prohibited) with don't have to (not necessary).",
      usageNoteRu: "Не путайте mustn't (запрещено) с don't have to (не обязательно).",
    },
  ),

  // ── grammar.conditional_0_1 ───────────────────────────────────────────────
  gp(
    'grammar.conditional_0_1',
    'zero_general_truths',
    'B1',
    'If + Present Simple, Present Simple',
    'If you heat water to 100°C, it boils.',
    'Zero conditional: general truths and rules.',
    'Нулевой кондиционал: общие истины и правила.',
  ),
  gp(
    'grammar.conditional_0_1',
    'first_real_future',
    'B1',
    'If + Present Simple, will + V1',
    'If it rains, we will stay home.',
    'First conditional: real future possibility.',
    'Первый кондиционал: реальная возможность в будущем.',
  ),
  gp(
    'grammar.conditional_0_1',
    'no_will_in_if_clause',
    'B1',
    'if-clause takes Present, not will',
    'If it rains... (not: If it will rain...)',
    'The if-clause uses Present Simple even though the meaning is future.',
    'Придаточное с if использует Present Simple, хотя значение — будущее.',
    { contrastExample: 'If it will rain, we will stay home. (wrong)' },
  ),
  gp(
    'grammar.conditional_0_1',
    'unless_negative_if',
    'B1',
    'unless = if ... not',
    "Unless you hurry, you'll miss the train.",
    'unless replaces a negative if-clause.',
    'unless заменяет отрицательное придаточное с if.',
  ),
];
